from typing import Protocol

from study_help_agent.capabilities.learning_notes.domain.models import GeneratedNote, SavedNote


class NoteRepository(Protocol):
    def save(self, note: GeneratedNote) -> SavedNote: ...
    def list_notes(self) -> list[dict]: ...
    def read(self, filename: str) -> str: ...
    def update(self, filename: str, content: str) -> None: ...
    def delete(self, filename: str) -> bool: ...
